apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: replicas.yaml

configMapGenerator:
  - name: myapp-config
    literals:
      - APP_ENV=production
